# Generated by Django 3.0.5 on 2025-11-25 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('description', models.TextField(verbose_name='Descripció')),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Música'), ('talk', 'Xerrades'), ('education', 'Educació'), ('sports', 'Esports'), ('entertainment', 'Entreteniment'), ('technology', 'Tecnologia'), ('art', 'Art i Creativitat'), ('other', 'Altres')], max_length=20, verbose_name='Categoria')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data i hora programada')),
                ('status', models.CharField(choices=[('scheduled', 'Programat'), ('live', 'En Directe'), ('finished', 'Finalitzat'), ('cancelled', 'Cancel·lat')], default='scheduled', max_length=20, verbose_name='Estat')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='Imatge de portada')),
                ('max_viewers', models.PositiveIntegerField(default=100, verbose_name='Màxim espectadors')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de creació')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualització')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Etiquetes')),
                ('stream_url', models.URLField(blank=True, max_length=500, verbose_name='URL del streaming')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Esdeveniment',
                'verbose_name_plural': 'Esdeveniments',
                'ordering': ['-created_at'],
            },
        ),
    ]
