# Generated by Django 4.1.13 on 2026-01-06 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Títol')),
                ('description', models.TextField(verbose_name='Descripció')),
                ('category', models.CharField(choices=[('gaming', '🎮 Gaming'), ('music', '🎵 Música'), ('technology', '💻 Tecnologia'), ('education', '📚 Educació'), ('art', '🎨 Art'), ('talk', '💬 Xerrada'), ('sports', '⚽ Esports'), ('entertainment', '🎭 Entreteniment')], default='gaming', max_length=20, verbose_name='Categoria')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data i hora programada')),
                ('status', models.CharField(choices=[('draft', 'Esborrany'), ('scheduled', 'Programat'), ('live', 'En directe'), ('finished', 'Finalitzat'), ('cancelled', 'Cancel·lat')], default='scheduled', max_length=20, verbose_name='Estat')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/', verbose_name='Miniatura')),
                ('max_viewers', models.PositiveIntegerField(default=100, verbose_name='Màxim espectadors')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacat')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Etiquetes')),
                ('stream_url', models.URLField(max_length=500, verbose_name='URL del stream')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de creació')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Data d'actualització")),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Esdeveniment',
                'verbose_name_plural': 'Esdeveniments',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
