# Generated by Django 4.1.13 on 2026-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
