# Generated by Django 4.1.13 on 2026-01-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='¿Eliminado?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Eliminado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Mensaje del chat',
                'verbose_name_plural': 'Mensajes del chat',
                'ordering': ['created_at'],
            },
        ),
    ]
